# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('class_desc', models.CharField(max_length=200)),
                ('category_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('lecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=50)),
                ('lecture_desc', models.CharField(max_length=200)),
                ('video_number', models.IntegerField(default=0)),
                ('class_id', models.IntegerField(default=0)),
            ],
        ),
    ]
