# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=50)),
                ('video_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
