# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20161122_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='klass_id',
            new_name='klass',
        ),
    ]
