# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_remove_klass_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classes.Category'),
        ),
    ]
