# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_lecture_lecture_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='klass',
        ),
        migrations.AddField(
            model_name='lecture',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classes.Category'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='klass_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='klass_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Klass',
        ),
    ]
