# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_lecture_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='klass_img',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
