# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_lecture_pub_date'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watch_history',
            field=models.ManyToManyField(to='classes.Lecture'),
        ),
    ]
